context:
  name: signal
  version: "1.4.8"

package:
  name: octave-${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/gnu-octave/octave-signal/releases/download/${{ version }}/signal-${{ version }}.tar.gz
  sha256: f5989b4f148e6f5b696a7b7ceee8c610140acf6084eb3e7eafbf0eb38df79a33
  target_directory: ${{ name }}

build:
  number: 0
  skip:
    - if: win or osx
      then: true
  script: |
    tar -czf ${{ name }}-${{ version }}.tar.gz ${{ name }}
    octave -W -H --eval "pkg install -global -verbose ${{ name }}-${{ version }}.tar.gz"

    mkdir -p $PREFIX/bin
    cp $RECIPE_DIR/post-link.sh $PREFIX/bin/.octave-${{ name }}-post-link.sh
    chmod +x $PREFIX/bin/.octave-${{ name }}-post-link.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - make
  host:
    - octave
    - octave-control
  run:
    - octave-control

tests:
  - script: |
      octave -W -H --eval "\
        pkg list; \
        pkg load signal; \
        disp('signal loaded') \
      "

about:
  homepage: https://github.com/gnu-octave/octave-signal
  license: GPL-3.0-or-later
  license_file: signal/COPYING
  summary: Signal processing tools for GNU Octave (filtering, windowing, spectral analysis)

extra:
  recipe-maintainers:
    - arjxn-py
